apiVersion: v1
kind: ConfigMap
metadata:
  name: middleman-config
data:
  PROVIDERS_CDN_URL: "https://soothe-vault.nyc3.cdn.digitaloceanspaces.com/providers.json"
  AUTH_TRUST_HOST: "http://localhost:3000"
  APP_URL: "http://localhost:3000"
  AUTH_URL: "http://localhost:3000"
  CHAIN_ID: "testnet"
  BLOCKCHAIN_PROTOCOL: "morse"
  OWNER_IDENTITY: "CHANGE_THIS"
  OWNER_EMAIL: "fake-support@igniter.com"
  TEMPORAL_URL: "temporal-frontend.default.svc.cluster.local:7233"
  TEMPORAL_NAMESPACE: "middleman"
  TEMPORAL_TASK_QUEUE: "middleman-operations"
