apiVersion: v1
kind: Service
metadata:
  name: provider
  namespace: default
spec:
  selector:
    app: provider
    component: web
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
