apiVersion: v1
kind: ConfigMap
metadata:
  name: provider-config
data:
  AUTH_TRUST_HOST: "http://localhost:3001"
  APP_URL: "http://localhost:3001"
  AUTH_URL: "http://localhost:3000"
  OWNER_IDENTITY: "82ba736e51e4f13fea40a2df567d34ef4a8d39a1"
  CHAIN_ID: "testnet"
  BLOCKCHAIN_PROTOCOL: "morse"
  OWNER_EMAIL: "julio@poktscan.com"
  TEMPORAL_URL: "__TEMPORAL_URL__"
  TEMPORAL_NAMESPACE: "__TEMPORAL_NAMESPACE_IN_DEV__"
  TEMPORAL_TASK_QUEUE: "__TEMPORAL_TASK_QUEUE_IN_DEV__"
