apiVersion: v1
kind: Secret
metadata:
  name: provider-secrets
type: Opaque
stringData:
  ENCRYPTION_IV: "REPLACE_IN_ENVIRONMENT"
  ENCRYPTION_KEY: "REPLACE_IN_ENVIRONMENT"
  AUTH_SECRET: "REPLACE_IN_ENVIRONMENT"
  APP_IDENTITY: "REPLACE_IN_ENVIRONMENT"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-provider-connection
type: Opaque
stringData:
  PGHOST: "postgresql.default.svc.cluster.local"
  PGUSER: "postgres"
  PGPASSWORD: "postgres"
  DATABASE_URL: "postgres://postgres:postgres@postgresql.default.svc.cluster.local:5432/provider?sslmode=disable"
  DB_NAME: "provider"
