apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleman
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleman
      component: web
  template:
    metadata:
      labels:
        app: middleman
        component: web
    spec:
      containers:
        - name: middleman
          image: igniter/middleman:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: middleman-config
            - secretRef:
                name: middleman-secrets
            - secretRef:
                name: postgres-middleman-connection
