apiVersion: v1
kind: Secret
metadata:
  name: middleman-secrets
  namespace: default
type: Opaque
stringData:
  AUTH_SECRET: "REPLACE_IN_ENVIRONMENT"
  COIN_MARKET_CAP_API_KEY: "REPLACE_IN_ENVIRONMENT"
  DATABASE_URL: "REPLACE_IN_ENVIRONMENT"
