apiVersion: v1
kind: Secret
metadata:
  name: middleman-secrets
type: Opaque
stringData:
  AUTH_SECRET: "REPLACE_IN_ENVIRONMENT"
  COIN_MARKET_CAP_API_KEY: "REPLACE_IN_ENVIRONMENT"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-middleman-connection
type: Opaque
stringData:
  PGHOST: "postgresql.default.svc.cluster.local"
  PGUSER: "postgres"
  PGPASSWORD: "postgres"
  DATABASE_URL: "postgres://postgres:postgres@postgresql.default.svc.cluster.local:5432/middleman?sslmode=disable"
  DB_NAME: "middleman"
