apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  storage:
    storageClass: standard
    size: 1Gi
  superuserSecret:
    name: postgres-secret
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
      secret:
        name: postgres-secrets
  enableSuperuserAccess: true
