apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleman-workflows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleman
      component: workflows
  template:
    metadata:
      labels:
        app: middleman
        component: workflows
    spec:
      containers:
        - name: middleman
          image: localhost:5001/middleman-workflows
          envFrom:
            - configMapRef:
                name: middleman-workflows-config
            - secretRef:
                name: postgres-middleman-connection
