apiVersion: v1
kind: ConfigMap
metadata:
  name: middleman-workflows-config
  namespace: default
data:
  TEMPORAL_URL: "REPLACE_IN_ENVIRONMENT"
  TEMPORAL_NAMESPACE: "REPLACE_IN_ENVIRONMENT"
  TEMPORAL_TASK_QUEUE: "REPLACE_IN_ENVIRONMENT"
  TEMPORAL_WORKFLOW_RETENTION: "REPLACE_IN_ENVIRONMENT"
