apiVersion: v1
kind: ConfigMap
metadata:
  name: middleman-config
  namespace: default
data:
  TEMPORAL_URL: "REPLACE_IN_ENVIRONMENT"
  AUTH_TRUST_HOST: "REPLACE_IN_ENVIRONMENT"
  APP_URL: "REPLACE_IN_ENVIRONMENT"

