resources:
  - postgres-secrets.yml
  - ../base
  - postgres-tls.yml
patches:
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: postgres
    path: ./patch-cluster.yml
