apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1
  storage:
    storageClass: local-path
    size: 1Gi
  tls:
    certificates:
      - secretRef: postgres-tls
        destinationPath: /server-tls
